import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import { BodyLoginPage, ButtonContainer, Container } from './styles';
import TextField from '@mui/material/TextField';
import { useForm } from 'react-hook-form';
import ErrorMessage from '../../components/error-meassage/errorMessage';
import DialogPopUp from '../../components/dialog-pop-up/dialogPopUp';
import { useState } from 'react';
import { useDispatch } from 'react-redux';
import { loginAction } from '../../sagas/actions/user';
import Image from 'next/image';

const Login = () => {
  const [openPopUp, setOpenPopUp] = useState(false);
  const dispatch = useDispatch();
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm();

  const onSave = (data) => {
    dispatch(loginAction(data));
  };

  const closePopUp = () => {
    setOpenPopUp(false);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BodyLoginPage>
        <Container>
          <Image
            src={'/logo.png'}
            alt={'logo'}
            width={'280px'}
            height={'72px'}
          />
          <div className={'container-input'}>
            <form onSubmit={handleSubmit(onSave)}>
              <TextField
                className={'inputs'}
                fullWidth
                name={'email'}
                error={errors.user}
                id="filled-basic"
                label="Usuário"
                variant="filled"
                {...register('email', { required: true })}
              />
              {errors.user && (
                <ErrorMessage text={'O campo Usuário é obrigatório'} />
              )}
              <TextField
                className={'inputs'}
                fullWidth
                id="filled-password-input"
                label="Senha"
                type="password"
                autoComplete="current-password"
                variant="filled"
                {...register('password', { required: true })}
              />
              {errors.password && (
                <ErrorMessage text={'O campo Senha é obrigatório'} />
              )}
              <ButtonContainer
                backgoundcolor={'#354545'}
                className={'inputs buttons-input'}
                fullWidth
                variant="contained"
                type={'submit'}
              >
                ENTRAR
              </ButtonContainer>
            </form>
            <ButtonContainer
              backgoundcolor={'#354545'}
              className={'inputs buttons-input'}
              fullWidth
              variant="contained"
              type={'button'}
              onClick={() => setOpenPopUp(true)}
            >
              CADASTRAR
            </ButtonContainer>
            <DialogPopUp
              title={`Cadastro`}
              openPopup={openPopUp}
              onClose={closePopUp}
            />
          </div>
        </Container>
      </BodyLoginPage>
    </div>
  );
};

export default Login;
