import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import { BodyLoginPage, ButtonContainer, Container } from './styles';
import TextField from '@mui/material/TextField';
import { useForm } from 'react-hook-form';
import { useEffect, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { loginAction } from '../../sagas/actions/user';
import ErrorMessage from '../../components/error-meassage/errorMessage';
import DialogPopUp from '../../components/dialog-pop-up/dialogPopUp';
import Image from 'next/image';
import { Alert, Snackbar } from '@mui/material';
import Router from 'next/router';

const Login = () => {
  const [openPopUp, setOpenPopUp] = useState(false);
  const [openError, setOpenError] = useState(false);
  const dispatch = useDispatch();
  const error = useSelector((state) => state?.error);
  const login = useSelector((state) => state?.logged);
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm();

  const onSave = (data) => {
    console.log(data);
    dispatch(loginAction(data));
  };

  const closePopUp = () => {
    setOpenPopUp(false);
  };

  useEffect(() => {
    if (!login) return;
    Router.push('/home');
  }, [login]);

  useEffect(() => {
    if (!error) return;
    setOpenError(true);
  }, [error]);

  return (
    <div className={styles.container}>
      <Snackbar
        open={openError}
        autoHideDuration={3000}
        onClose={() => setOpenError(false)}
        anchorOrigin={{ vertical: 'top', horizontal: 'center' }}
      >
        <Alert
          onClose={() => setOpenError(false)}
          severity="error"
          sx={{ width: '100%' }}
        >
          {error?.message}
        </Alert>
      </Snackbar>
      <Head>
        <title>Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BodyLoginPage>
        <Container>
          <Image
            src={'/logo.png'}
            alt={'logo'}
            width={'280px'}
            height={'72px'}
          />
          <div className={'container-input'}>
            <form onSubmit={handleSubmit(onSave)}>
              <TextField
                style={{ marginTop: '50px' }}
                fullWidth
                name={'email'}
                error={errors.user}
                id="filled-basic"
                label="Usuário"
                variant="filled"
                {...register('email', { required: true })}
              />
              {errors.user && (
                <ErrorMessage text={'O campo Usuário é obrigatório'} />
              )}
              <TextField
                style={{ marginTop: '50px' }}
                fullWidth
                id="filled-password-input"
                label="Senha"
                type="password"
                autoComplete="current-password"
                variant="filled"
                {...register('password', { required: true })}
              />
              {errors.password && (
                <ErrorMessage text={'O campo Senha é obrigatório'} />
              )}
              <ButtonContainer
                style={{
                  backgroundColor: '#354545',
                  marginTop: '50px',
                  height: '50px',
                }}
                fullWidth
                variant="contained"
                type={'submit'}
              >
                ENTRAR
              </ButtonContainer>
            </form>
            <ButtonContainer
              style={{
                backgroundColor: '#354545',
                marginTop: '50px',
                height: '50px',
              }}
              fullWidth
              variant="contained"
              type={'button'}
              onClick={() => setOpenPopUp(true)}
            >
              CADASTRAR
            </ButtonContainer>
            <DialogPopUp
              title={`Cadastro de produto`}
              openPopup={openPopUp}
              onClose={closePopUp}
            />
          </div>
        </Container>
      </BodyLoginPage>
    </div>
  );
};

export default Login;
