import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Input from '../components/input/input';
import { BodyLoginPage, Container } from './styles';

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BodyLoginPage>
        <Container>
          <Input placeHolder={'Usuario'} />
          <Input placeHolder={'Senha'} type={'password'} />
        </Container>
      </BodyLoginPage>
    </div>
  );
};

export default Home;
