export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';
export const GET_ALL_PRODUCTS_BY_USER_EMAIL_SUCCESS =
  'GET_ALL_PRODUCTS_BY_USER_EMAIL_SUCCESS';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CREATE_PRODUCTS_SUCCESS = 'CREATE_PRODUCTS_SUCCESS';
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const PURCHASE = 'PURCHASE';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAIL = 'PURCHASE_FAIL';
export const GET_ALL_PURCHASE_BY_USER_ID_ACTION =
  'GET_ALL_PURCHASE_BY_USER_ID_ACTION';
export const GET_ALL_PURCHASE_BY_USER_ID_ACTION_SUCCESS =
  'GET_ALL_PURCHASE_BY_USER_ID_ACTION_SUCCESS';
