import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Input} from "../components/input/input";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Input placeHolder={"Usuario"} />
    </div>
  )
}
